%YAML 1.0
---

input_images_folder:
  - /data/auv_resident/zed_video_samples_in_air/calib_videos/left_images/
  - /data/auv_resident/zed_video_samples_in_air/calib_videos/right_images/

use_mono_focal: # (if 0: fx != fy)
  - 1
  - 1

dist_model: # (rad1, rad2, rad3, radtan4, radtan5, radtan8, kannalabrandt)
  - radtan5
  - radtan5

prior_fov: # Prior FOV of the camera in degrees
  - 70.0
  - 70.0

target_type: "aprilgrid" # (chessboard / aprilgrid)

target_nb_rows: 6
target_nb_cols: 8

# Follows Kalibr convention: https://github.com/ethz-asl/kalibr/wiki/calibration-targets
tag_size: 0.06
tag_space: 0.25 # ratio of size of tags wrt. size of space between tags.

debug: 0